### ISSUE TITLE
helper prints debug unwanted debug output

### ISSUE THREAD

**Issue by fholzer** [akamai-open/AkamaiOPEN-edgegrid-node#14]
Every `eg.send()` invocation will print some `Preparedbody:` line. A bit annoying...

https://github.com/akamai-open/AkamaiOPEN-edgegrid-node/blob/master/src/helpers.js#L29

**Comment by ktyacke** [comment]
Pull requests are welcome ;-)

**Comment by fholzer** [comment]
Actually this is already being dealt with in #13.
