### ISSUE TITLE
A couple question about running the app

### ISSUE THREAD

**Issue by iyip** [akamai-open/AkamaiOPEN-edgegrid-node#16]
1) I cloned the repo and followed readme to do
npm install --save edgegrid
I got this error: npm WARN install Refusing to install edgegrid as a dependency of itself
so I did npm install
2) How do I run the app?
3) In which file can I find the '/path/to/.edgerc', and change it according to my env? I have .edgerc in my ~ directory

**Comment by ktyacke** [comment]
Hi iyip,
I think you might be a bit confused about how you install node packages. You do not need to clone the project, unless you intend to link to it locally. If you simply want to use the Node Edgegrid module in your Node.js project, you first you have to install node.js in the environment where you plan to run your application (this could be your local machine or a remote server). Next you have to initiate your node.js application, or manually create your package.json file for your node app. Once you've done this, you can then run `npm install --save edgegrid` from the root of your project. This will download and install the Node Edgegrid project from NPM (https://www.npmjs.com/package/edgegrid) and save it as a dependency of your project. 

Then to link to your .edgerc file, you just have to change '/path/to/.edgerc' to the path of the .edgerc file on your machine ('/users/iyip/.edgerc' or whatever it is for your file).

I hope this helps,

Kyle
