### ISSUE TITLE
Fix Chaining or Remove from readme

### ISSUE THREAD

**Issue by cpitt** [akamai-open/AkamaiOPEN-edgegrid-node#18]
In the readme it gives an [example of chaining call ](https://github.com/akamai-open/AkamaiOPEN-edgegrid-node#chaining). However, it appears that functionality was removed for example [this commit](https://github.com/akamai-open/AkamaiOPEN-edgegrid-node/commit/1cf44e78da9044fcd15f04f27ee7b9f8599a41e3). 

I'd be more than happy to submit a PR either removing the documentation or going through and adding back in the return statements I just need to know which direction the maintainers would like to take.

I personally like chaining but that's me.

**Comment by ktyacke** [comment]
Hi cpitt,
Thanks for pointing this out. So at this point you've been able to confirm that chaining is not functioning? Unfortunately the commit you linked to didn't work (404) so I wasn't able to review that piece. PR's are always welcome, and I think chaining is a valuable feature and should be included, so please feel free to submit.

Cheers,

Kyle

**Comment by cpitt** [comment]
Updated the original post to include [working link](https://github.com/akamai-open/AkamaiOPEN-edgegrid-node/commit/1cf44e78da9044fcd15f04f27ee7b9f8599a41e3#diff-e1d62d8c4965edf0e532dfa19da0891fL23). I'll start on a PR for that shortly.

**Comment by ktyacke** [comment]
Sounds good, thanks!

**Comment by pradeep-mishra** [comment]
Hi,
When this functionality is expected to be pushed on npm, looks like latest npm module still have this issue.
