### ISSUE TITLE
EdgeGrid.prototype.send should use node style callbacks

### ISSUE THREAD

**Issue by cpitt** [akamai-open/AkamaiOPEN-edgegrid-node#23]
Currently the EdgeGrid.protype.send method accepts a callback. On error this callback is executed with the first argument as `(error)`, on success however to callback executed with arguments `(body, response)`

```
EdgeGrid.prototype.send = function(callback) {
  request(this.request, function(error, response, body) { 
    if (error) {
      callback(error)
      return
    }
    if (helpers.isRedirect(response.statusCode)) {
      this._handleRedirect(response, callback);
      return;
    }

    callback(body, response);
  }.bind(this));

  return this;
};
```

I propose this be changed to conform to [node style callbacks](https://nodejs.org/api/errors.html#errors_node_js_style_callbacks) and to preserve the request callback signature of `(err, response, body)`

```
EdgeGrid.prototype.send = function(callback) {
  request(this.request, function(error, response, body) { 
    if (error) {
      callback(error)
      return
    }
    if (helpers.isRedirect(response.statusCode)) {
      this._handleRedirect(response, callback);
      return;
    }

    callback(null, response, body);
  }.bind(this));

  return this;
};
```

This IMO is the expected behavior and should make it easier to use things like Bluebirds promisify to generate promises for this library.

**Comment by ktyacke** [comment]
Merged Pull Request and updated README file to reflect new node style callbacks. Bumped version to 3.0 since this is a breaking change, and pushed latest to NPM.
