### ISSUE TITLE
Get products

### ISSUE THREAD

**Issue by farkhad-alizade** [akamai-open/AkamaiOPEN-edgegrid-node#8]
I have some trouble in getting products from akami api using nodejs AkamaiOPEN-edgegrid-node.
Here is my code:
eg.auth({
        path: '/billing-usage/v1/products',
        method: 'POST',
        headers: {'reportSources': '[{\'id\':\'123\',\'type\':\'reportGroup\'},{\'id\':\'123\',\'type\':\'contract\'},{\'id\':\'123\',\'type\':\'reportGroup\'}]',
            'startDate': '{\'month\':1, \'year\': 2015}',
            'endDate': '{\'month\':11, \'year\': 2015}'}
    });
    
    eg.send(function(error, response, body) {
        console.log(error);
        //console.log(response);
        console.log(body);
    });    
 
like in example.
Also i have tried change headers key name to body, still getting result 400 Bad request.

**Comment by ktyacke** [comment]
What is the response you are receiving? Also, could you post the full code?

**Comment by fholzer** [comment]
This works for me:

    var param = "reportSources=" + encodeURIComponent('[{"id":"' + contractId + '","type":"contract"}]') +
        "&startDate=" + encodeURIComponent('{"month":4, "year": 2016}') +
        "&endDate=" + encodeURIComponent('{"month":4, "year": 2016}');

    eg.auth({
        path: '/billing-usage/v1/products',
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: param
    });

    eg.send(console.log);

**Comment by ktyacke** [comment]
@fholzer Thanks for tagging in on this! Appreciate the help =] 

@farkhad-alizade If you're still having issues I'd recommend posting to the Akamai OPEN Community site (there is much better coverage on there for helping to answer these types of questions). Also, there is a great knowledge base there and it may already contain the info you're looking for.
https://community.akamai.com/community/developer
